# Extra Environment
export PYTHONSTARTUP="/home/bkopin/.pythonstartup.py"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Git aliases



# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias l="ls -ls -tr "
alias utar="tar -xf"
alias b="cd .."
# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git pip virtualenv) 

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/opt/sbt/sbt/bin:/opt/scala/scala-2.10.2/bin:/opt/sbt/sbt/bin:/opt/scala/scala-2.10.2/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


# ************************************
# From http://habrahabr.ru/post/162339/
# ************************************

#Включить автодополнение 
autoload -U compinit promptinit 
compinit
promptinit

# Корректировка ввода
setopt CORRECT_ALL

# Если в слове есть ошибка, предложить исправить её
SPROMPT="Error! Do you need %r insted %R? ([Y]es/[N]o/[E]dit/[A]bort) "

# Не нужно всегда вводить cd
# просто наберите нужный каталог и окажитесь в нём
setopt autocd

# При совпадении первых букв слова вывести меню выбора
zstyle ':completion:*' menu select=long-list select=0
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}


# Aliases
alias ls='ls --color=auto'
alias lla='ls -la --color=auto'
alias grep='grep --colour=auto'


# #  History
# # хранить историю в указанном файле
# export HISTFILE=~/.zsh_history
# # максимальное число команд, хранимых в сеансе
# export HISTSIZE=10000
# export SAVEHIST=$HISTSIZE
# # включить историю команд
# setopt APPEND_HISTORY
# # убрать повторяющиеся команды, пустые строки и пр.
# setopt HIST_IGNORE_ALL_DUPS
# setopt HIST_IGNORE_SPACE
# setopt HIST_REDUCE_BLANKS
